# configuration for https://travis-ci.org/jsalatas/faircoinj
sudo: false
dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
install: true
script:
  - gradle clean build

notifications:
  irc:
    channels: "irc.freenode.net#faircoinj"
    skip_join: true
